interface Incident {
  incidentID: string; // AlphaNumeric -Autogenerated unique ID
  requestedBy: string; // emailID of user created this request
  requestedFor: string; //emailID of user for whom this request was created.; this field should be compared with UserName of User Interface
  effectiveDate: string; // date from which this change should be effective
  environmentType: string; // prod or non-prod
  application: string; // PC or portal or anyother server
  description: string; // details regarding the request
  createdTime: string;
  updatedBy: string;
  updatedTime: string;
  status: string;
  environment: string;
}

export default Incident;
